### ISSUE TITLE
Therapy episodes

### ISSUE THREAD

**Issue by emmavestesson** [ramses-antibiotics/ramses-package#67]
Hi, 
In the `TherapyEpisode()` function help, could it be clearer that the id refers to the therapy_id that is created when you add the prescription table to the database and not the patient or prescription id? It is clear from the vignette but not from the help files (and the vignettes are not automatically built when installing from github). The current description is 'a character therapy episode identifier', maybe the word `therapy_id` could be included to make it clear exactly what id you require? I think the character part is unnecessary - my `therapy_id` variable is numeric and it works just fine. 

Thanks, 

Emma

**Comment by peterdutey** [comment]
Thank you Emma you are right. 
This should be better with 607daf1
Thank you!
Peter
